---
title: "Prelim_results"
output: html_document
date: "2023-03-06"
---
```{r packages}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(vegan)
library(phyloseq)
library(forcats)
```

```{r functions}
# from MiscMetabar
as_binary_otu_table <- function(physeq, min_number = 1) {
  if (!inherits(physeq, "phyloseq")) {
    stop("physeq must be a phyloseq object")
  }
  res <- physeq
  res@otu_table[res@otu_table >= min_number] <- 1
  res@otu_table[res@otu_table < min_number] <- 0
  return(res)
}

clean_physeq <- function(physeq,
                         remove_empty_samples = TRUE,
                         remove_empty_taxa = T, clean_samples_names = TRUE,
                         clean_samples_names = TRUE,
                         silent = FALSE,
                         verbose = FALSE) {
  if (clean_samples_names) {
    if (!is.null(physeq@refseq)) {
      if (sum(!names(physeq@refseq) %in% taxa_names(physeq)) > 0) {
        names(physeq@refseq) <- taxa_names(physeq)
        if (!silent) {
          message("Change the samples names in refseq slot")
        }
      }
    }
    if (!is.null(physeq@tax_table)) {
      if (sum(!rownames(physeq@tax_table) %in% taxa_names(physeq)) > 0) {
        rownames(physeq@tax_table) <- taxa_names(physeq)
        if (!silent) {
          message("Change the taxa names in tax_table slot")
        }
      }
    }

    if (!is.null(physeq@sam_data)) {
      if (sum(!rownames(physeq@sam_data) %in% sample_names(physeq)) > 0) {
        rownames(physeq@sam_data) <- sample_names(physeq)
        if (!silent) {
          message("Change the samples names in sam_data slot")
        }
      }
    }
  }

  if (sum(grepl("^0", "", sample_names(physeq)) > 0) && !silent) {
    message("At least one sample name start with a zero.
    That can be a problem for some phyloseq functions such as 
    plot_bar and psmelt.")
  }

  new_physeq <- physeq

  if (remove_empty_taxa) {
    if (sum(taxa_sums(new_physeq) == 0) > 0) {
      new_physeq <- subset_taxa(physeq, taxa_sums(physeq) > 0)
    }
  }
  if (remove_empty_samples) {
    if (sum(sample_sums(new_physeq) == 0) > 0) {
      new_physeq <- subset_samples(new_physeq, sample_sums(physeq) > 0)
    }
  }

  if (verbose) {
    message(paste(
      "Supress", ntaxa(physeq) - ntaxa(new_physeq), "taxa (",
      names(taxa_sums(physeq) > 0), ") and",
      nsamples(physeq) - nsamples(new_physeq),
      "sample(s) (", names(sample_sums(physeq) > 0), ")."
    ))
  } else if (!silent) {
    message(paste(
      "Supress", ntaxa(physeq) - ntaxa(new_physeq), "taxa and",
      nsamples(physeq) - nsamples(new_physeq),
      "samples."
    ))
  }

  return(new_physeq)
}

pairwise.adonis2 <- function(x, data, strata = NULL, nperm=999, ... ) {

#describe parent call function 
ststri <- ifelse(is.null(strata),'Null',strata)
fostri <- as.character(x)
#list to store results

#copy model formula
   x1 <- x
# extract left hand side of formula
  lhs <- x1[[2]]
# extract factors on right hand side of formula 
  rhs <- x1[[3]]
# create model.frame matrix  
  x1[[2]] <- NULL   
  rhs.frame <- model.frame(x1, data, drop.unused.levels = TRUE) 

# create unique pairwise combination of factors 
  co <- combn(unique(as.character(rhs.frame[,1])),2)

# create names vector   
  nameres <- c('parent_call')
  for (elem in 1:ncol(co)){
  nameres <- c(nameres,paste(co[1,elem],co[2,elem],sep='_vs_'))
  }
#create results list  
  res <- vector(mode="list", length=length(nameres))
  names(res) <- nameres

#add parent call to res 
res['parent_call'] <- list(paste(fostri[2],fostri[1],fostri[3],', strata =',ststri, ', permutations',nperm ))

  
#start iteration trough pairwise combination of factors  
 for(elem in 1:ncol(co)){

#reduce model elements  
	if(inherits(eval(lhs),'dist')){	
	    xred <- as.dist(as.matrix(eval(lhs))[rhs.frame[,1] %in% c(co[1,elem],co[2,elem]),
		rhs.frame[,1] %in% c(co[1,elem],co[2,elem])])
	}else{
	xred <- eval(lhs)[rhs.frame[,1] %in% c(co[1,elem],co[2,elem]),]
	}
	
	mdat1 <-  data[rhs.frame[,1] %in% c(co[1,elem],co[2,elem]),] 

# redefine formula
	if(length(rhs) == 1){
		xnew <- as.formula(paste('xred',as.character(rhs),sep='~'))	
		}else{
		xnew <- as.formula(paste('xred' , 
					paste(rhs[-1],collapse= as.character(rhs[1])),
					sep='~'))}
					
#pass new formula to adonis
	if(is.null(strata)){
	ad <- adonis2(xnew,data=mdat1, ... )
	}else{
	perm <- how(nperm = nperm)
    setBlocks(perm) <- with(mdat1, mdat1[,ststri])
    ad <- adonis2(xnew,data=mdat1,permutations = perm, ... )}
	
  res[nameres[elem+1]] <- list(ad[1:5])
  }
  #names(res) <- names  
  class(res) <- c("pwadstrata", "list")
  return(res)
} 

plot_pie<-function(physeq, title.,condition,COL.TAXO. = COL.TAXO){
  # Extract sample data.frame and merge with taxonomy information
  # The resulting data.frame is decomposed to have a
  df<-psmelt(physeq)

  inner_tax<-aggregate(Abundance ~ Phylum+Description, data=df,sum,simplify=T)
  outer_tax<-aggregate(Abundance ~ Class+Description, data=df,sum,simplify=T)

  plot_pie_vector(subset(inner_tax,Description==condition, select = "Abundance",drop= TRUE),
                  subset(outer_tax,Description==condition, select = "Abundance",drop= TRUE),
                  title = title.,
                  COL.TAXO = COL.TAXO., EDG = 200)
  list_taxa<-list(
    inner=subset(inner_tax,Description==condition, select = 1,drop= TRUE),
    outer=subset(outer_tax,Description==condition, select = 1,drop= TRUE))
  return(list_taxa)
}

ggrare <- function(physeq_object, step = 10, label = NULL, color = NULL, plot = TRUE, parallel = FALSE, se = TRUE) {

  x <- methods::as(phyloseq::otu_table(physeq_object), "matrix")
  if (phyloseq::taxa_are_rows(physeq_object)) { x <- t(x) }

  ## This script is adapted from vegan `rarecurve` function
  tot <- rowSums(x)
  S <- rowSums(x > 0)
  nr <- nrow(x)

  rarefun <- function(i) {
    cat(paste("rarefying sample", rownames(x)[i]), sep = "\n")
    n <- seq(1, tot[i], by = step)
    if (n[length(n)] != tot[i]) {
      n <- c(n, tot[i])
    }
    y <- vegan::rarefy(x[i, ,drop = FALSE], n, se = se)
    if (nrow(y) != 1) {
      rownames(y) <- c(".S", ".se")
      return(data.frame(t(y), Size = n, Sample = rownames(x)[i]))
    } else {
      return(data.frame(.S = y[1, ], Size = n, Sample = rownames(x)[i]))
    }
  }
  if (parallel) {
    out <- parallel::mclapply(seq_len(nr), rarefun, mc.preschedule = FALSE)
  } else {
    out <- lapply(seq_len(nr), rarefun)
  }
  df <- do.call(rbind, out)

  # Get sample data
  if (!is.null(phyloseq::sample_data(physeq_object, FALSE))) {
    sdf <- methods::as(phyloseq::sample_data(physeq_object), "data.frame")
    sdf$Sample <- rownames(sdf)
    data <- merge(df, sdf, by = "Sample")
    labels <- data.frame(x = tot, y = S, Sample = rownames(x))
    labels <- merge(labels, sdf, by = "Sample")
  }

  # Add, any custom-supplied plot-mapped variables
  if ( length(color) > 1 ) {
    data$color <- color
    names(data)[names(data) == "color"] <- deparse(substitute(color))
    color <- deparse(substitute(color))
  }

  if ( length(label) > 1 ) {
    labels$label <- label
    names(labels)[names(labels) == "label"] <- deparse(substitute(label))
    label <- deparse(substitute(label))
  }

  p <- ggplot2::ggplot(data = data,
                       ggplot2::aes_string(x = "Size",
                                           y = ".S",
                                           group = "Sample",
                                           color = color))

  p <- p + ggplot2::labs(x = "Sequence Sample Size (Nb of reads)", y = "Number of ASV/OTU occurence")

  if (!is.null(label)) {
    p <- p + ggplot2::geom_text(data = labels,
                                ggplot2::aes_string(x = "x",
                                                    y = "y",
                                                    label = label,
                                                    color = color),
                       size = 4, hjust = 0)
  }

  p <- p + ggplot2::geom_line()
  if (se) { ## add standard error if available
    p <- p +
      ggplot2::geom_ribbon(ggplot2::aes_string(ymin = ".S - .se",
                                               ymax = ".S + .se",
                                               color = NULL,
                                               fill = color),
                           alpha = 0.2)
  }
  if (plot) {
    plot(p)
  }
  invisible(p)
}
```

```{r importation}
# tax-eco table 
## only ECM and saprotrophs
setwd("H:/REDACTION/RESULTS/cutting_ecm/TRANSF_DATA2")
taxeco <- read.table("tax_table.txt",header=T,sep="\t") # change #N/A in excel in NA
length(taxeco)
taxeco[,c(3:length(taxeco))] <- lapply(taxeco[,c(3:length(taxeco))], as.factor) 
rownames(taxeco) <- taxeco$Cluster_ID

# otu table
otu <- read.table("otu_table.txt",header=F,sep="\t",na.strings = T) 
otu = setNames(data.frame(t(otu[,-1])), otu[,1]) # transpose + 1st column (ie samples set as header
## samples = columns, otu abundance = rows
colnames(otu)[1] <- "Cluster_ID" # after transposing, resolving pb with headers
nrow(otu)

# sample data
sam <- read.table("sample_table.txt",header=T,sep="\t",na.strings = T) 
sam[sam==""] <- NA # filling the blanck by NAs
length(sam)
rownames(sam) <- sam$sample_id # after transposing, resolving pb with headers

# subset guilds (saprotroph - ectomycorrizal)
ecm <- subset(taxeco,taxeco$primary_lifestyle=="ectomycorrhizal") %>% arrange(desc(Cluster_Size))
sapr <- subset(taxeco,taxeco$primary_lifestyle!="ectomycorrhizal")
```

```{r supress OTU non ecto/no sapro}
otu_filtered <- merge(otu, taxeco, by = "Cluster_ID",sort=T) # using taxeco (already filtered by ecm and sapr) to filter otu from other guilds

# semi_join(otu, taxeco, by = "Cluster_ID") # not working because not similar df


sam_filtered <- sam[sam$sample_id %in% colnames(otu_filtered),] # keep the rows (ie samples) that appear in others tables
# if 0 obs, in df -> check column names (may differs among datasets)
rownames(sam_filtered) <- sam_filtered[,1]

rownames(otu_filtered) <- otu_filtered[,1] 
which(colnames(otu_filtered)=="sPCR_neg_2") # merge 2 dataframe, but we just want to keep otu (with the good rows)
otu_filtered2 <- subset(otu_filtered[c(1:513),c(2:162),])
taxeco2 <- subset(taxeco[,c(3:length(taxeco)),]) 
```

```{r trasnforming df into matrixes}
# useful functions
## str() 
## class()
## dplyr::join()

# transforming dataframes into matrixes for phyloseq functions (otu,tax)
otu_filtered3 <- matrix(as.numeric(unlist(otu_filtered2)), 
                        ncol = ncol(otu_filtered2),
                        nrow = nrow(otu_filtered2))
taxeco3 <- matrix(as.character(unlist(taxeco2)), 
                        ncol = ncol(taxeco2),
                        nrow = nrow(taxeco2))

# attributing rownanmes after being deleted from matrix transformation
rownames(otu_filtered3) <- rownames(otu_filtered2)
colnames(otu_filtered3) <- colnames(otu_filtered2)
rownames(taxeco3) <- rownames(taxeco2)
colnames(taxeco3) <- colnames(taxeco2)
```

```{r otu <1% suppresion}
# transforming abundance matrix to relative
otu_relative <- prop.table(otu_filtered3, margin=2) # margin = 2 -> column sum and relative abundances

# verification
## rowsum
verif_sum <- colSums(otu_relative) %>% summary() %>% print() # ok if 1 and some NAs

## for 3 - c10 c100
### total read sample3 =744 
relat_3c10 <- (19/744) %>% print()
relat_3c100 <- (25/744) %>% print() 
which(otu_relative==relat_3c10, arr.ind = T)
which(otu_relative==relat_3c100, arr.ind = T) # good 

# creating a new matrix where <1% reads are deleted 
otu_sup0.01 <- ifelse(otu_relative>0.01,otu_filtered3,0) 
```

```{r physeq objects}
# creating the physeq objects 
otu_phy <- otu_table(otu_sup0.01, taxa_are_rows = TRUE)
taxeco_phy <- tax_table(taxeco3)
sam_phy <- sample_data(sam_filtered)

# general physeq object
physeq <- phyloseq(otu_phy,taxeco_phy,sam_phy) 
sample_names(physeq) # missing the controls and negatives
```

```{r physeq susbsets}
# subsetting based on sites and guilds 
ecm_phy <- subset_taxa(physeq, primary_lifestyle=="ectomycorrhizal") 
ecm_phy <- subset_samples(ecm_phy, site=!"control") %>% clean_physeq(remove_empty_samples = T,remove_empty_taxa = T, clean_samples_names = T)
sapr_phy <- subset_taxa(physeq, primary_lifestyle!="ectomycorrhizal")

fanga <- subset_samples(physeq, physeq@sam_data$site=="Fangamon") %>% clean_physeq(remove_empty_samples = T,remove_empty_taxa = T, clean_samples_names = T)
hala <- subset_samples(physeq, physeq@sam_data$site=="Halasen") %>% clean_physeq(remove_empty_samples = T,remove_empty_taxa = T, clean_samples_names = T)
hala5 <- subset_samples(physeq, physeq@sam_data$site=="Halasen_p_5") %>% clean_physeq(remove_empty_samples = T,remove_empty_taxa = T, clean_samples_names = T)
  
fanga_ecm <- subset_samples(ecm_phy, ecm_phy@sam_data$site=="Fangamon") %>% clean_physeq(remove_empty_samples = T,remove_empty_taxa = T, clean_samples_names = T)
hala_ecm <- subset_samples(ecm_phy, ecm_phy@sam_data$site=="Halasen") %>% clean_physeq(remove_empty_samples = T,remove_empty_taxa = T, clean_samples_names = T)
hala5_ecm <- subset_samples(ecm_phy, ecm_phy@sam_data$site=="Halasen_p_5") %>% clean_physeq(remove_empty_samples = T,remove_empty_taxa = T, clean_samples_names = T)

fanga_sapr <- subset_samples(sapr_phy, sapr_phy@sam_data$site=="Fangamon") %>% clean_physeq(remove_empty_samples = T,remove_empty_taxa = T, clean_samples_names = T)
hala_sapr <- subset_samples(sapr_phy, sapr_phy@sam_data$site=="Halasen") %>% clean_physeq(remove_empty_samples = T,remove_empty_taxa = T, clean_samples_names = T)
hala5_sapr <- subset_samples(sapr_phy, sapr_phy@sam_data$site=="Halasen_p_5") %>% clean_physeq(remove_empty_samples = T,remove_empty_taxa = T, clean_samples_names = T)

# abundance -> boolean
fanga_ecm_pa <- as_binary_otu_table(fanga_ecm) %>% clean_physeq(remove_empty_samples = T,remove_empty_taxa = T, clean_samples_names = T)
hala_ecm_pa <- as_binary_otu_table(hala_ecm) %>% clean_physeq(remove_empty_samples = T,remove_empty_taxa = T, clean_samples_names = T) 
hala5_ecm_pa <- as_binary_otu_table(hala5_ecm) %>% clean_physeq(remove_empty_samples = T,remove_empty_taxa = T, clean_samples_names = T)

fanga_sapr_pa <- as_binary_otu_table(fanga_sapr) %>% clean_physeq(remove_empty_samples = T,remove_empty_taxa = T, clean_samples_names = T)
hala_sapr_pa <- as_binary_otu_table(hala_sapr) %>% clean_physeq(remove_empty_samples = T,remove_empty_taxa = T, clean_samples_names = T)
hala5_sapr_pa <- as_binary_otu_table(hala5_sapr) %>% clean_physeq(remove_empty_samples = T,remove_empty_taxa = T, clean_samples_names = T)
```

```{r transfo variables}
fanga_sam <- lapply(fanga@sam_data, as.factor) %>% as.data.frame()
hala_sam <- lapply(hala@sam_data, as.factor) %>% as.data.frame()
hala5_sam <- lapply(hala5@sam_data, as.factor) %>% as.data.frame()

sample_data(fanga_ecm)$year_factor <- as.factor(sample_data(fanga_ecm)$year)
sample_data(hala_ecm)$year_factor <- as.factor(sample_data(hala_ecm)$year)
```

```{r matrix simple otu-sam}
fanga_ecm_samotu <- data.frame(fanga_ecm@sam_data,t(fanga_ecm@otu_table)) 
hala_ecm_samotu <- data.frame(hala_ecm@sam_data,t(hala_ecm@otu_table))
hala_ecm_samotu <- lapply(hala_ecm_samotu[,1:10], as.factor) %>% as.data.frame()
hala5_ecm_samotu <- data.frame(hala5_ecm@sam_data,t(hala5_ecm@otu_table))
```

