---
title: "Preliminary_results"
output: html_document
date: "2023-03-02"
editor_options: 
  chunk_output_type: console
---
# PACKAGES AND IMPORTATION DATA
```{r packages}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(vegan)
```
```{r functions}
outersect <- function(x, y) {
  sort(c(setdiff(x, y),
         setdiff(y, x)))
} # extract uncommon values between x - y 
```

# IMPORTATION DATA
```{r }
# tax-eco table
#setwd("H:/REDACTION/RESULTS/cutting_ecm/TRANSF_DATA") # to change, depending on which computer i am working on
tax_table <- read.table("tax_table.txt",header=T,sep="\t") # change #N/A in excel in NA
length(tax_table)
tax_table[,c(3:10)] <- lapply(tax_table[,c(3:10)], as.factor) 

#data run
run_data <- read.table("run_data.txt",header=T,sep="\t",na.strings=T,dec=".")
colnames(run_data)

# clust all
raw_clust <- read.table("raw_clusters.txt",header=T,sep="\t",na.strings=T,dec=".") %>% 
arrange(desc(Cluster_Size))
raw_clust[raw_clust==""] <- NA
raw_clust[,4] <- as.character(raw_clust[,4])

raw_f_clust <- subset(raw_clust,!grepl("PLANT|NF",raw_clust[,4]))

# subset guilds
ecm <- subset(tax_table,tax_table$primary_lifestyle=="ectomycorrhizal") %>% arrange(desc(Cluster_Size))
sapr <- subset(tax_table,tax_table$primary_lifestyle!="ectomycorrhizal") %>% arrange(desc(Cluster_Size))
```
# DATA RUN
```{r results mm}
colnames(run_data) 

run_data[,1]# 2 runs
run_data[,25] # 98,5% similarity clustering

# run 1
run_data[1,2] # total nb of pyro reads
run_data[1,3] # sequences passing quality control (QC)
run_data[1,2]-run_data[1,3] # sequences deleted

# run 2
run_data[2,2] # total nb of pyro reads
run_data[2,3] # sequences passing quality control (QC)
run_data[2,2]-run_data[2,3] # sequences deleted

# scata taxa attribution 

## no IDed sequences
is.na(raw_clust[,4]) %>% summary() # 1145 clusters ID / 4050 
pourc_id <- 1145/4050*100; pourc_id # autoID (especially the most abundant clusters)
# ID for 1000s first TODO

## NF sequences
grep("PLANT|NF", raw_clust[,4], value = TRUE) %>% length() # 82 non-fungi clusters IDed 

# total VS conserve
## nb clusters
nrow(raw_clust) # all
nrow(ecm) # ecm among 1000st more abundant Fungi clusters 
pourc_ecm <- 204/1000*100; pourc_ecm # 20% ECM guild among Fungi

## nb reads
run_data[3,2]
raw_total_read <- sum(raw_f_clust$Cluster_Size); raw_total_read ## TODO: exlcude plants to have proper pourcentages values
ecm_total_read <-sum(ecm$Cluster_Size); ecm_total_read
pourc_nb_read_ecm <- ecm_total_read/raw_total_read*100; pourc_nb_read_ecm # pourc nb read conserved/ nb read 
summary(ecm$Cluster_Size) # min, mean, max of ecm reads
```

# TAXECO TABLE
## OVERVIEW_DATA
```{r general}
summary(run_data)
summary(raw_clust)
summary(ecm)
summary(sapr)
levels(droplevels(ecm$Genus))
levels(droplevels(sapr$Genus))

summary(ecm$Cluster_Size)

hist_cluster_size <- ggplot(ecm, 
       aes(x=Cluster_Size))+
geom_histogram(bins=20,breaks=seq(12,2985 ,by=100),color="black", fill="darkseagreen")+
  scale_y_continuous(name="number of clusters")+
  scale_x_continuous(name="number of reads", breaks=seq(12,2985 ,by=100))+
  theme(axis.text.x=element_text(color="coral4", size=8, angle=60))+
  ggtitle("Distribution of the cluster size for ECM OTUs") 

hist_cluster_size
```
```{r SAC nb read}
sac_f_raw <- ggplot(raw_f_clust, aes(x=c(1:3968),y=cumsum(Cluster_Size)))+   geom_line(color="red")+
  geom_point(size=0.7,alpha=0.5)+
  coord_cartesian(xlim=c(0,3968),ylim=c(0,244367))+
  scale_y_continuous(name="cumulative cluster size", breaks=seq(0,244367,by=25000))+
  scale_x_continuous(name="number of cluster", breaks=seq(0,3968 ,by=200))+
  geom_vline(xintercept=1000,lwd=0.6,colour="red",)+ 
  annotate("text", x = 1050, y = 25000, label="1000 first clusters conserved", size = 4, angle=0, color = "red", hjust = 0)+
  annotate("text", x= 1050, y= 15000, label="93.65% of total reads", size = 4, angle=0, color = "red", hjust = 0)+
  theme(axis.text.x=element_text(color="coral4", size=8, angle=60))+
  ggtitle("Cumulative cluster size curve from all fungi clusters") 

?hjust
sac_f_raw

read_1000 <- sum(raw_f_clust[c(1:1000),2]); read_1000
read_3968 <- sum(raw_f_clust[c(1001:3968),2]); read_3968
read_total <- sum(raw_f_clust[,2])
pourc_read_kept <- read_1000/read_total*100; pourc_read_kept
```

```{r missing samples}
# considering physeq objects (ecm_phy,hala_ecm, hala5_ecm, fanga_ecm have been cleaned (sample supress if 0) by clean_pq() )
colnames(hala_sam)
summary(hala_sam[,c(2,5:8)])
table(hala_sam$plot,hala_sam$treatment)

# for ecm-sapr
summary(sam$sample_id)
summary(physeq@sam_data$sample_id)
miss_sam_clust_ecmsapr <- anti_join(x = sam, y = physeq@sam_data) # return all rows from x without a match in y.
miss_sam_clust_ecmsapr$sample_id # samples deleted after bioinformatic processes (scata, first 1000s clusters, ecm-sapr guilds)

# for ecm only
summary(sam$sample_id)
summary(ecm_phy@sam_data$sample_id)
miss_sam_clust_ecm <- anti_join(x = sam, y = ecm_phy@sam_data)
miss_sam_clust_ecm$sample_id
# 8 PCR neg => good control,
# what about ITS standard ?

clipr::write_clip(miss_sam_clust_ecm$sample_id) # to copy dataframe or vector
# controls and na 
miss_sam_clust_ctrl <- anti_join(x = sam_controls_na, y = ecm_phy@sam_data)
miss_sam_clust_ctrl$sample_id

length(miss_sam_clust_ctrl$sample_id)
length(row.names(sam_controls_na)) # every control and NA are suppressed from the dataset (because 0 occurence of clusters)

# hala
miss_sam_clust_hala <- anti_join(x = sam_hala[,1:7], y = hala_ecm@sam_data[,1:7]) # exclude specification column because we changed factor values for this column
miss_sam_clust_hala$sample_id

# hala5
miss_sam_clust_hala5 <- anti_join(x = sam_hala5, y = hala5_ecm@sam_data)
miss_sam_clust_hala5$sample_id

# fanga
miss_sam_clust_fanga <- anti_join(x = sam_fanga, y = fanga_ecm@sam_data)
miss_sam_clust_fanga$sample_id

# check if count is good (total missing samples VS sum of missing samples per site)
length(miss_sam_clust_ecm$sample_id)/(length(miss_sam_clust_hala$sample_id)+length(miss_sam_clust_hala5$sample_id)+length(miss_sam_clust_fanga$sample_id)+length(miss_sam_clust_ctrl$sample_id)) 
# =1 -> all good 

not_samples_kept
length(miss_sam_clust_ecm$sample_id) 
length(miss_sam_clust_ctrl$sample_id) 
length(miss_sam_clust_hala$sample_id) # total 6 
length(miss_sam_clust_hala5$sample_id)# total 4 (including 4)
length(miss_sam_clust_fanga$sample_id)# total 20

length(rownames(sam_hala))
length(rownames(sam_hala5))
length(rownames(sam_fanga))
```

```{r DESIGN SAMPLES}

nrow(otu) # total number of all clusters (ie fungi ecm or no-ecm, plants)
colnames(otu)

# samples missing post scata (ie not present in the OTU matrix from clustering = no match between ITS4 - ITS7 tags)

samples_missing_postscata <- outersect(x = sam_no_match$samples_match, y = sam_no_match$samples_all) # antijoin but for columns : extract samples not in common (missing from initial samples design)
samples_missing_postscata <- dput(as.character(samples_missing_postscata)) # convert into the format c(x; y; ...; z)
sam[sam$sample_id %in% samples_missing_postscata,] # showing samples with site and plots information missing 
## 5 controls; 3 Halasen; 2 Halasen_p5, 1 Q1; 6 PCR_neg
## total missing = 17

sample_count_design <- length(rownames(sam)) # 178 samples total design + controls)

# design samples per site 
length(rownames(sam_hala))
length(rownames(sam_hala5))
length(rownames(sam_fanga))

# sample count
length(rownames(sam_controls_na)) # 19 (12 NAs + 7 controls)
sum(is.na(sam_controls_na$site)) 
real_sample_count <- (length(rownames(sam))-length(rownames(sam_controls_na))) %>%
  print() # 159 sites samples


colnames(otu)
s_id_controls <- sam_controls_na$sample_id[sam_controls_na$site == "control"] %>%
  na.exclude()  # what are the samples_id of controls samples ? 
s_id_controls <- dput(as.character(s_id_controls))

col_control_kept <- which(colnames(otu) %in% s_id_controls, arr.ind = F) 
colnames(otu)[col_control_kept]

controls_kept <- c("sITS-standard2", "sITS-standard1", "sPCR_neg_1", "sPCR_neg_2", "sQ2", "s49", "s97") # 2 ITS; 2 PCR; 1Q; 2 controls 

161-7+5 
# 161 = total samples kept after scata
# -7  = controls kept after scata
# +5  = site samples missing 
## final 159 samples -> ALL GOOD 
```

```{r potential contamination ?}
which(samples_kept_pq>0, arr.ind = T) # location where values of controls have reads
clusters_reads_inctrl <- rownames(which(samples_kept_pq>0, arr.ind = T)) %>% as.factor()
levels(clusters_reads_inctrl) # clusters where we found reads in controls samples 
## -> should we erase them for dataset ? 
## surely, imo 
```

