---
title: "Prelim_results"
output: html_document
date: "2023-03-06"
---
```{r packages}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(vegan)
library(phyloseq)
```

```{r importation}
# tax-eco table # only ECM and saprotrophs
taxeco <- read.table("tax_table.txt",header=T,sep="\t")
# change #N/A in excel in NA
length(taxeco)
taxeco[,c(3:10)] <- lapply(taxeco[,c(3:10)], as.factor) 
rownames(taxeco) <- taxeco$Cluster_ID

# otu table
otu <- read.table("otu_table.txt",header=F,sep="\t",na.strings = T) 
otu = setNames(data.frame(t(otu[,-1])), otu[,1])
# transpose + 1st column (ie samples set as header
colnames(otu)[1] <- "Cluster_ID"
otu <- otu[-4051,]

# sample data
sam <- read.table("sample_table.txt",header=T,sep="\t",na.strings = T) 
sam[sam==""] <- NA
length(sam)

# subset guilds (saprotroph - ectomycorrizal)
ecm <- subset(taxeco,taxeco$primary_lifestyle=="ectomycorrhizal") %>% arrange(desc(Cluster_Size))
sapr <- subset(taxeco,taxeco$primary_lifestyle!="ectomycorrhizal")

```

```{r supress OTU non ecto/no sapro}
otu_filtered <- merge(otu, taxeco, by = "Cluster_ID") # maybe should i used join functions?

sam_filtered <- sam[sam$sample_order %in% colnames(otu_filtered),] # keep the rows (ie samples) that appear in others tables

rownames(otu_filtered) <- otu_filtered[,1] 
which(colnames(otu_filtered)=="PCR_neg_2") # merge 2 dataframe, but we just want to keep otu (with the good rows)
otu_filtered2 <- subset(otu_filtered[c(1:513),c(2:162),])
taxeco2 <- subset(taxeco[,c(3:length(taxeco)),]) 
```

```{r physeq object}
# str()
# class()

otu_filtered3 <- matrix(as.numeric(unlist(otu_filtered2)), 
                        ncol = ncol(otu_filtered2),
                        nrow = nrow(otu_filtered2))
taxeco3 <- matrix(as.character(unlist(taxeco2)), 
                        ncol = ncol(taxeco2),
                        nrow = nrow(taxeco2))
rownames(otu_filtered3) <- rownames(otu_filtered2)
colnames(otu_filtered3) <- colnames(otu_filtered2)
rownames(taxeco3) <- rownames(taxeco2)
colnames(taxeco3) <- colnames(taxeco2)

otu_phy <- otu_table(otu_filtered3, taxa_are_rows = TRUE)
taxeco_phy <- tax_table(taxeco3)
sam_phy <- sample_data(sam_filtered)

physeq <- phyloseq(otu_phy,taxeco_phy,sam_phy) 
sample_names(physeq) # missing the controls and negatives

ecm <- select_tax_table(physeq, )


  select_tax_table(Phylum, Genus:Species) %>%
  select_sample_data(!dplyr::contains("Barcode"))
  
  

fanga <- subset_samples(physeq, physeq@sam_data$site=="Fangamon")
hala <- subset_samples(physeq, physeq@sam_data$site=="Halasen")
hala5 <- subset_samples(physeq, physeq@sam_data$site=="Halasen_p_5")

ecm_phy <- subset_taxa(physeq, primary_lifestyle=="ectomycorrhizal")
sapr_phy <- subset_taxa(physeq, primary_lifestyle!="ectomycorrhizal")
  
ecm_fanga <- subset_samples(ecm_phy, physeq@sam_data$site=="Fangamon")
ecm_hala <- subset_samples(ecm_phy, physeq@sam_data$site=="Halasen")
ecm_hala5 <- subset_samples(ecm_phy, physeq@sam_data$site=="Halasen_p_5")

sapr_fanga <- subset_samples(sapr_phy, physeq@sam_data$site=="Fangamon")
sapr_hala <- subset_samples(sapr_phy, physeq@sam_data$site=="Halasen")
sapr_hala5 <- subset_samples(sapr_phy, physeq@sam_data$site=="Halasen_p_5")
```

```{r plotting try}
str(fanga@sam_data$treatment)

plot_bar(physeq, x="Class")
plot_bar(physeq, x="Fruitbody_type_template")
plot_bar(physeq, x="site", fill="Class")
plot_bar(fanga, x="treatment", fill="Class")
plot_bar(hala, x="treatment", fill="Class")
plot_bar(ecm_phy, x="site", fill="Class")

plot_bar(ecm_hala, x="treatment", fill="Genus")
plot_bar(sapr_hala, x="treatment", fill="Genus")

nmds <- ordinate(
  physeq = physeq, 
  method = "NMDS", 
  distance = "bray")

phyloseq::plot_ordination(physeq, color = "Site") + 
    geom_point() 

ggplot(physeq, aes(x = Site, y = Abundance, fill = Class)) + 
  geom_bar(stat = "identity") 
```


